### ISSUE TITLE
Azurechatgpt?

### ISSUE THREAD

**Issue by natowi** [microsoft/azure-openai-in-a-day-workshop#16]
Hopefully not too off topic, but I don´t know where else to ask: Where did https://github.com/microsoft/azurechatgpt go? Was it renamed or removed? Why?

**Comment by ravineshappypie** [comment]
It seems this repository (https://github.com/microsoft/azurechatgpt ) has been removed. Can anyone please mention the reason?

**Comment by juju4** [comment]
Few forks are still public https://github.com/search?q=Azure+ChatGPT%3A+Private+secure+ChatGPT+for+internal+enterprise+use&type=repositories

**Comment by pierrelouisbescond** [comment]
> Hopefully not too off topic, but I don´t know where else to ask: Where did https://github.com/microsoft/azurechatgpt go? Was it renamed or removed? Why?

I was wondering the same 🤔 I had planned to explore it when I am back from holidays and the original repo has disappeared in between 😱 

> Few forks are still public https://github.com/search?q=Azure+ChatGPT%3A+Private+secure+ChatGPT+for+internal+enterprise+use&type=repositories

This repo seems to be the copy of the last update from Microsoft (14/08) by the original author (thivy): https://github.com/seanbrar/azurechatgpt/commits/main

**Comment by natowi** [comment]
A mirror of the original is available on archive.org.

To restore the repository download the bundle

wget https://archive.org/download/github.com-microsoft-azurechatgpt_-_2023-08-14_17-56-05/microsoft-azurechatgpt_-_2023-08-14_17-56-05.bundle

and run:

 git clone microsoft-azurechatgpt_-_2023-08-14_17-56-05.bundle
 
 But I am still curious for the removal reasons. The repository was trending, so why remove it without any comment?

**Comment by KeysAU** [comment]
Also would like to know why the repo was removed

**Comment by pierrelouisbescond** [comment]
It think it's back in a slightly different format: https://github.com/microsoft/azurechat

**Comment by natowi** [comment]
They probably had to rename it to avoid confusion with OpenAI "Chatgtp" for legal reasons
